### ISSUE TITLE
Peer Review Lab 2 - Francesco Di Gangi s301793

### ISSUE THREAD

**Issue by FDG2801** [KrzysztofKleist/CI-22#4]
Hello there, 

I'd like to start with your **readme**. I think it is pretty clear and explain in a very good way your solution and your fitness implementation.

Now, let's talk about the code.
As I can see, you used a model similar to the one the professor used for the one-max problem! Great! 

The first thing I can notice is that the functions have a self-explanatory name. I think this is good indeed. 
I also think that create a list of genome with `0` and `1` is great and probably a fast way to implement the population. 

The first plot (also great) is good enough to see that your implementation works fine with `N=5`. 

Moving on to superior values of `N`, I can see that it is acceptable also for 10, 20 (especially after the deadline), 100 (there is a slight difference). With 500 and 1000 your solution seems to be very expensive, as you said on your readme.

I think you might want to take a look at the fitness function. I think that with your idea to limit the population and the offspring size it could improve. Also, you can try a strict limit for the number of max generations. Another comment that I want to do is please try to comment your code. 

Overall tho I think this is a great job! Keep going! :)

**Comment by KrzysztofKleist** [comment]
Thank you for your review!
I already implemented some changes, but all of them after the deadline. I will try to improve it more with your suggestions.
